### ISSUE TITLE
Adversarial weight set to 0 by default

### ISSUE THREAD

**Issue by xunhuang1995** [edenton/drnet#5]
Hi, I noticed that the "advWeight" is set to zero by default. However, when I run the MNIST example with default parameters, I can still get disentangled results, which is different from what Figure 4 suggests. Any thoughts?

**Comment by fredyjl** [comment]
same here on pytorch implementation. Haven't tested on the other datasets.

**Comment by edenton** [comment]
Hey, yes you are correct .. if the dataset is simple enough, and the pos dimension is *small enough* then you will get a disentangled representation. For example, for NORB, if you set advWeight = 0 and pose_dim = 2, it will work wonderfully. But if you set advWeight = 0  pose_dim = 10, it won't work (but if pose_dim = 10 and advWeight > 0 then it will). 

Essentially, having a tight information bottleneck in the pose pathway performs the same function as the adversarial loss, i.e. to only represent information not present in the content image. you can think of the adversarial loss as a more sophisticated way of doing what a simple bottleneck does, and a way of performing that function even when you don't know what the 'right' dimensionality of the pose vector should be. 

Hope that made sense!
